// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildGraph(arg1) {
  return window['go']['main']['App']['BuildGraph'](arg1);
}

export function BuildGraphFocused(arg1, arg2) {
  return window['go']['main']['App']['BuildGraphFocused'](arg1, arg2);
}

export function BuildGraphFromCode(arg1, arg2) {
  return window['go']['main']['App']['BuildGraphFromCode'](arg1, arg2);
}

export function BuildGraphFromObsidian(arg1, arg2) {
  return window['go']['main']['App']['BuildGraphFromObsidian'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClaudeSessionProgress(arg1, arg2) {
  return window['go']['main']['App']['ClaudeSessionProgress'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteEntity(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntity'](arg1, arg2);
}

export function DeleteMemoryFile(arg1) {
  return window['go']['main']['App']['DeleteMemoryFile'](arg1);
}

export function DeleteRelation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRelation'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DoCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['DoCommit'](arg1, arg2, arg3);
}

export function EnrichTask(arg1) {
  return window['go']['main']['App']['EnrichTask'](arg1);
}

export function GenerateArticle(arg1, arg2) {
  return window['go']['main']['App']['GenerateArticle'](arg1, arg2);
}

export function GenerateCommit(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GenerateCommit'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetEmbeddingConfig() {
  return window['go']['main']['App']['GetEmbeddingConfig']();
}

export function GetGraph(arg1) {
  return window['go']['main']['App']['GetGraph'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function IndexProject(arg1) {
  return window['go']['main']['App']['IndexProject'](arg1);
}

export function IndexSearch() {
  return window['go']['main']['App']['IndexSearch']();
}

export function InstallMCP() {
  return window['go']['main']['App']['InstallMCP']();
}

export function ListClaudeProjects() {
  return window['go']['main']['App']['ListClaudeProjects']();
}

export function ListClaudeSessions(arg1) {
  return window['go']['main']['App']['ListClaudeSessions'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListMemoryFiles(arg1) {
  return window['go']['main']['App']['ListMemoryFiles'](arg1);
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListTaskRuns(arg1) {
  return window['go']['main']['App']['ListTaskRuns'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MCPStatus() {
  return window['go']['main']['App']['MCPStatus']();
}

export function MatchKnowledge(arg1, arg2) {
  return window['go']['main']['App']['MatchKnowledge'](arg1, arg2);
}

export function NewConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewConversation'](arg1, arg2, arg3);
}

export function ReadClaudeSession(arg1, arg2) {
  return window['go']['main']['App']['ReadClaudeSession'](arg1, arg2);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RenameEntity(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameEntity'](arg1, arg2, arg3);
}

export function RepoStatus(arg1) {
  return window['go']['main']['App']['RepoStatus'](arg1);
}

export function ResumeCommand(arg1, arg2) {
  return window['go']['main']['App']['ResumeCommand'](arg1, arg2);
}

export function ReviewTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReviewTask'](arg1, arg2, arg3);
}

export function RunTask(arg1) {
  return window['go']['main']['App']['RunTask'](arg1);
}

export function SaveProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveProvider'](arg1, arg2);
}

export function SearchSessions(arg1, arg2) {
  return window['go']['main']['App']['SearchSessions'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetDefaults(arg1, arg2) {
  return window['go']['main']['App']['SetDefaults'](arg1, arg2);
}

export function SetEmbeddingConfig(arg1, arg2) {
  return window['go']['main']['App']['SetEmbeddingConfig'](arg1, arg2);
}

export function SetEmbeddingMode(arg1) {
  return window['go']['main']['App']['SetEmbeddingMode'](arg1);
}

export function StopGeneration(arg1) {
  return window['go']['main']['App']['StopGeneration'](arg1);
}

export function TermResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TermResize'](arg1, arg2, arg3);
}

export function TermStart(arg1) {
  return window['go']['main']['App']['TermStart'](arg1);
}

export function TermStartResume(arg1, arg2) {
  return window['go']['main']['App']['TermStartResume'](arg1, arg2);
}

export function TermStop(arg1) {
  return window['go']['main']['App']['TermStop'](arg1);
}

export function TermWrite(arg1, arg2) {
  return window['go']['main']['App']['TermWrite'](arg1, arg2);
}

export function TestEmbedding() {
  return window['go']['main']['App']['TestEmbedding']();
}

export function UninstallMCP() {
  return window['go']['main']['App']['UninstallMCP']();
}

export function UpdateEntityObservations(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEntityObservations'](arg1, arg2, arg3);
}

export function UpdateSpec(arg1, arg2) {
  return window['go']['main']['App']['UpdateSpec'](arg1, arg2);
}

export function WriteMemoryFile(arg1, arg2) {
  return window['go']['main']['App']['WriteMemoryFile'](arg1, arg2);
}
