// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackfillMemories() {
  return window['go']['main']['App']['BackfillMemories']();
}

export function ClassifyTask(arg1) {
  return window['go']['main']['App']['ClassifyTask'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListMemories() {
  return window['go']['main']['App']['ListMemories']();
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function NewConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewConversation'](arg1, arg2, arg3);
}

export function RecallMemories(arg1, arg2) {
  return window['go']['main']['App']['RecallMemories'](arg1, arg2);
}

export function Recommend(arg1, arg2) {
  return window['go']['main']['App']['Recommend'](arg1, arg2);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RoutingTable() {
  return window['go']['main']['App']['RoutingTable']();
}

export function SaveProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveProvider'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetDefaults(arg1, arg2) {
  return window['go']['main']['App']['SetDefaults'](arg1, arg2);
}

export function StopGeneration(arg1) {
  return window['go']['main']['App']['StopGeneration'](arg1);
}

export function SummarizeConversation(arg1) {
  return window['go']['main']['App']['SummarizeConversation'](arg1);
}
