// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {claudedata} from '../models';
import {model} from '../models';
import {main} from '../models';
import {routing} from '../models';
import {provider} from '../models';

export function BackfillMemories():Promise<number>;

export function BuildGraph(arg1:string):Promise<graph.Graph>;

export function BuildGraphFocused(arg1:string,arg2:string):Promise<graph.Graph>;

export function ClassifyTask(arg1:string):Promise<string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

export function DeleteMemoryFile(arg1:string):Promise<void>;

export function GenerateArticle(arg1:string,arg2:string):Promise<string>;

export function GetGraph(arg1:string):Promise<graph.Graph>;

export function IndexProject(arg1:string):Promise<void>;

export function ListClaudeProjects():Promise<Array<claudedata.Project>>;

export function ListClaudeSessions(arg1:string):Promise<Array<claudedata.SessionMeta>>;

export function ListConversations():Promise<Array<model.Conversation>>;

export function ListMemories():Promise<Array<main.MemoryEntry>>;

export function ListMemoryFiles(arg1:string):Promise<Array<claudedata.MemoryFile>>;

export function ListMessages(arg1:string):Promise<Array<model.Message>>;

export function ListModels(arg1:string):Promise<Array<string>>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function NewConversation(arg1:string,arg2:string,arg3:string):Promise<model.Conversation>;

export function ReadClaudeSession(arg1:string,arg2:string):Promise<Array<claudedata.SessionMessage>>;

export function RecallMemories(arg1:string,arg2:string):Promise<Array<model.MemoryHit>>;

export function Recommend(arg1:string,arg2:string):Promise<main.Recommendation>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function RoutingTable():Promise<routing.Table>;

export function SaveProvider(arg1:provider.Config,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:Array<string>):Promise<number>;

export function SetDefaults(arg1:string,arg2:string):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function SummarizeConversation(arg1:string):Promise<model.Memory>;

export function TermResize(arg1:number,arg2:number):Promise<void>;

export function TermStart():Promise<void>;

export function TermStop():Promise<void>;

export function TermWrite(arg1:string):Promise<void>;

export function WriteMemoryFile(arg1:string,arg2:string):Promise<void>;
